### ISSUE TITLE
error with eobs data

### ISSUE THREAD

**Issue by Rolandisimo1** [kulits2/3D-BKDE#5]
got an error with a condor from the peru study.  has e-obs data.  I corrected the height_above_ellipsoid column name and then stilll got this error

error:
One input must be smaller than the other in every dimension.

<img width="914" alt="Screenshot 2024-03-31 at 9 39 57 AM" src="https://github.com/kulits2/3D-BKDE/assets/19862446/740de682-cfb8-4f6f-b9c2-9b122c4c40a4">

<img width="424" alt="Screenshot 2024-03-31 at 9 40 32 AM" src="https://github.com/kulits2/3D-BKDE/assets/19862446/bbc0c261-1448-4589-a9f5-a973e4c6eb26">

**Comment by kulits2** [comment]
Hi, @Rolandisimo1.

Thanks for testing the app and reporting the issue. Unfortunately, I don't have enough information to investigate the error, though if you provide 1) a complete error log, 2) the specific dataset that triggered the problem, and 3) any configuration details necessary to replicate your setup, I'd be happy to help you debug and resolve this.

Peter

**Comment by Rolandisimo1** [comment]
Hi Peter, thanks for looking into this. Here is the data set, logs, and settings.  I tried changing the settings a little bit.

Roland

[HPAIPE006-7961.csv](https://github.com/kulits2/3D-BKDE/files/14823496/HPAIPE006-7961.csv)




Many Apps have been [deprecated](https://docs.moveapps.org/#/app_deprecation)
 and renewed. We recommend use of the new Apps. See details in our [news item](https://www.moveapps.org/news#2024-03-08).
MoveApps logo
BETA
Copyright © MoveApps 2024
3dvulture: Workflow Instance 001 
Movebank Location
App Outputs

move2_loc to MovingPandas
App Outputs
Remove pin

3D Binned Kernel Density Estimation
Error details

3D Binned Kernel Density Estimation – Logs
     2024-03-31 13:22:35.678 ERROR: app will be started with configuration: {'freq': '1h', 'max_seg_len': '6h', 'z_col': 'height.above.ellipsoid', 'kernel_radius': 5, 'kernel_sigma': 1, 'lat_grid_dim': 100, 'lon_grid_dim': 100, 'alt_grid_dim': 10, 'percentile': 99.5, 'show_topo': True}
     2024-03-31 13:22:35.696 ERROR: storing error to /tmp/error_file.txt
     2024-03-31 13:22:35.696 ERROR: Traceback (most recent call last):
     2024-03-31 13:22:35.696 ERROR:   File "/opt/co-pilot-python/sdk.py", line 30, in <module>
     2024-03-31 13:22:35.696 ERROR:     sdk = MoveAppsSdk(active_hooks=hooks)
     2024-03-31 13:22:35.697 ERROR:   File "/opt/co-pilot-python/sdk.py", line 23, in __init__
     2024-03-31 13:22:35.697 ERROR:     executor.execute()
     2024-03-31 13:22:35.697 ERROR:   File "/opt/co-pilot-python/sdk/moveapps_execution.py", line 33, in execute
     2024-03-31 13:22:35.697 ERROR:     raise exception
     2024-03-31 13:22:35.697 ERROR:   File "/opt/co-pilot-python/sdk/moveapps_execution.py", line 29, in execute
     2024-03-31 13:22:35.697 ERROR:     output = self.__call_app(data)
     2024-03-31 13:22:35.697 ERROR:   File "/opt/co-pilot-python/sdk/moveapps_execution.py", line 76, in __call_app
     2024-03-31 13:22:35.697 ERROR:     outputs = self._pm.hook.execute(data=data, config=self.env.app_configuration)
     2024-03-31 13:22:35.698 ERROR:   File "/opt/conda/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
     2024-03-31 13:22:35.698 ERROR:     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
     2024-03-31 13:22:35.698 ERROR:   File "/opt/conda/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
     2024-03-31 13:22:35.698 ERROR:     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
     2024-03-31 13:22:35.698 ERROR:   File "/opt/conda/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
     2024-03-31 13:22:35.698 ERROR:     return outcome.get_result()
     2024-03-31 13:22:35.699 ERROR:   File "/opt/conda/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
     2024-03-31 13:22:35.699 ERROR:     raise ex[1].with_traceback(ex[2])
     2024-03-31 13:22:35.699 ERROR:   File "/opt/conda/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
     2024-03-31 13:22:35.699 ERROR:     res = hook_impl.function(*args)
     2024-03-31 13:22:35.699 ERROR:   File "/opt/co-pilot-python/app/app.py", line 66, in execute
     2024-03-31 13:22:35.700 ERROR:     self.execute_once(data, app_config, traj_i)
     2024-03-31 13:22:35.700 ERROR:   File "/opt/co-pilot-python/app/app.py", line 83, in execute_once
     2024-03-31 13:22:35.701 ERROR:     assert app_config.z_col in traj.df, f"`{app_config.z_col}` is not in the `Trajectory` object"
     2024-03-31 13:22:35.701 ERROR: AssertionError: `height.above.ellipsoid` is not in the `Trajectory` object
     2024-03-31 13:33:14.214 ERROR: app will be started with configuration: {'freq': '1h', 'max_seg_len': '6h', 'z_col': 'height.above.ellipsoid', 'kernel_radius': 5, 'kernel_sigma': 1, 'lat_grid_dim': 100, 'lon_grid_dim': 100, 'alt_grid_dim': 10, 'percentile': 99.5, 'show_topo': True}
     2024-03-31 13:33:14.230 ERROR: storing error to /tmp/error_file.txt
     2024-03-31 13:33:14.231 ERROR: Traceback (most recent call last):
     2024-03-31 13:33:14.231 ERROR:   File "/opt/co-pilot-python/sdk.py", line 30, in <module>
     2024-03-31 13:33:14.232 ERROR:     sdk = MoveAppsSdk(active_hooks=hooks)
     2024-03-31 13:33:14.232 ERROR:   File "/opt/co-pilot-python/sdk.py", line 23, in __init__
     2024-03-31 13:33:14.232 ERROR:     executor.execute()
     2024-03-31 13:33:14.233 ERROR:   File "/opt/co-pilot-python/sdk/moveapps_execution.py", line 33, in execute
     2024-03-31 13:33:14.233 ERROR:     raise exception
     2024-03-31 13:33:14.234 ERROR:   File "/opt/co-pilot-python/sdk/moveapps_execution.py", line 29, in execute
     2024-03-31 13:33:14.234 ERROR:     output = self.__call_app(data)
     2024-03-31 13:33:14.234 ERROR:   File "/opt/co-pilot-python/sdk/moveapps_execution.py", line 76, in __call_app
     2024-03-31 13:33:14.235 ERROR:     outputs = self._pm.hook.execute(data=data, config=self.env.app_configuration)
     2024-03-31 13:33:14.236 ERROR:   File "/opt/conda/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
     2024-03-31 13:33:14.237 ERROR:     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
     2024-03-31 13:33:14.238 ERROR:   File "/opt/conda/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
     2024-03-31 13:33:14.238 ERROR:     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
     2024-03-31 13:33:14.240 ERROR:   File "/opt/conda/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
     2024-03-31 13:33:14.241 ERROR:     return outcome.get_result()
     2024-03-31 13:33:14.248 ERROR:   File "/opt/conda/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
     2024-03-31 13:33:14.249 ERROR:     raise ex[1].with_traceback(ex[2])
     2024-03-31 13:33:14.249 ERROR:   File "/opt/conda/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
     2024-03-31 13:33:14.250 ERROR:     res = hook_impl.function(*args)
     2024-03-31 13:33:14.250 ERROR:   File "/opt/co-pilot-python/app/app.py", line 66, in execute
     2024-03-31 13:33:14.251 ERROR:     self.execute_once(data, app_config, traj_i)
     2024-03-31 13:33:14.251 ERROR:   File "/opt/co-pilot-python/app/app.py", line 83, in execute_once
     2024-03-31 13:33:14.252 ERROR:     assert app_config.z_col in traj.df, f"`{app_config.z_col}` is not in the `Trajectory` object"
     2024-03-31 13:33:14.252 ERROR: AssertionError: `height.above.ellipsoid` is not in the `Trajectory` object
     2024-03-31 13:35:09.611 ERROR: app will be started with configuration: {'freq': '1h', 'max_seg_len': '6h', 'z_col': 'height_above_ellipsoid', 'kernel_radius': 5, 'kernel_sigma': 1, 'lat_grid_dim': 100, 'lon_grid_dim': 100, 'alt_grid_dim': 10, 'percentile': 99.5, 'show_topo': True}
     2024-03-31 13:35:09.711 INFO : make: Entering directory '/tmp/tmpjhzduf8x/SRTM1_ELLIP'
     2024-03-31 13:35:09.728 INFO : curl -s -o spool/South/S16W074_wgs84.tif.temp https://opentopography.s3.sdsc.edu/raster/SRTM_GL1_Ellip/SRTM_GL1_Ellip_srtm/South/S16W074_wgs84.tif && mv spool/South/S16W074_wgs84.tif.temp spool/South/S16W074_wgs84.tif
     2024-03-31 13:35:10.686 ERROR: storing error to /tmp/error_file.txt
     2024-03-31 13:35:10.688 ERROR: Traceback (most recent call last):
     2024-03-31 13:35:10.688 ERROR:   File "/opt/co-pilot-python/sdk.py", line 30, in <module>
     2024-03-31 13:35:10.688 ERROR:     sdk = MoveAppsSdk(active_hooks=hooks)
     2024-03-31 13:35:10.689 ERROR:   File "/opt/co-pilot-python/sdk.py", line 23, in __init__
     2024-03-31 13:35:10.689 ERROR:     executor.execute()
     2024-03-31 13:35:10.690 ERROR:   File "/opt/co-pilot-python/sdk/moveapps_execution.py", line 29, in execute
     2024-03-31 13:35:10.690 ERROR:     output = self.__call_app(data)
     2024-03-31 13:35:10.691 ERROR:   File "/opt/co-pilot-python/sdk/moveapps_execution.py", line 76, in __call_app
     2024-03-31 13:35:10.691 ERROR:     outputs = self._pm.hook.execute(data=data, config=self.env.app_configuration)
     2024-03-31 13:35:10.691 ERROR:   File "/opt/conda/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
     2024-03-31 13:35:10.692 ERROR:     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
     2024-03-31 13:35:10.693 ERROR:   File "/opt/conda/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
     2024-03-31 13:35:10.693 ERROR:     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
     2024-03-31 13:35:10.693 ERROR:   File "/opt/conda/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
     2024-03-31 13:35:10.694 ERROR:     res = hook_impl.function(*args)
     2024-03-31 13:35:10.694 ERROR:   File "/opt/co-pilot-python/app/app.py", line 66, in execute
     2024-03-31 13:35:10.694 ERROR:     self.execute_once(data, app_config, traj_i)
     2024-03-31 13:35:10.695 ERROR:   File "/opt/co-pilot-python/app/app.py", line 189, in execute_once
     2024-03-31 13:35:10.695 ERROR:     occ = f(p1_x, p1_y, p2_x, p2_y, z, start_time, end_time)
     2024-03-31 13:35:10.696 ERROR:   File "/opt/conda/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
     2024-03-31 13:35:10.696 ERROR:     return fun(*args, **kwargs)
     2024-03-31 13:35:10.696 ERROR:   File "/opt/conda/lib/python3.9/site-packages/jax/_src/pjit.py", line 250, in cache_miss
     2024-03-31 13:35:10.697 ERROR:     outs, out_flat, out_tree, args_flat, jaxpr = _python_pjit_helper(
     2024-03-31 13:35:10.697 ERROR:   File "/opt/conda/lib/python3.9/site-packages/jax/_src/pjit.py", line 158, in _python_pjit_helper
     2024-03-31 13:35:10.697 ERROR:     args_flat, _, params, in_tree, out_tree, _, jaxpr = infer_params_fn(
     2024-03-31 13:35:10.698 ERROR:   File "/opt/conda/lib/python3.9/site-packages/jax/_src/api.py", line 300, in infer_params
     2024-03-31 13:35:10.699 ERROR:     return pjit.common_infer_params(pjit_info_args, *args, **kwargs)
     2024-03-31 13:35:10.699 ERROR:   File "/opt/conda/lib/python3.9/site-packages/jax/_src/pjit.py", line 499, in common_infer_params
     2024-03-31 13:35:10.699 ERROR:     jaxpr, consts, canonicalized_out_shardings_flat = _pjit_jaxpr(
     2024-03-31 13:35:10.700 ERROR:   File "/opt/conda/lib/python3.9/site-packages/jax/_src/pjit.py", line 961, in _pjit_jaxpr
     2024-03-31 13:35:10.700 ERROR:     jaxpr, final_consts, out_type = _create_pjit_jaxpr(
     2024-03-31 13:35:10.700 ERROR:   File "/opt/conda/lib/python3.9/site-packages/jax/_src/linear_util.py", line 345, in memoized_fun
     2024-03-31 13:35:10.701 ERROR:     ans = call(fun, *args)
     2024-03-31 13:35:10.701 ERROR:   File "/opt/conda/lib/python3.9/site-packages/jax/_src/pjit.py", line 914, in _create_pjit_jaxpr
     2024-03-31 13:35:10.701 ERROR:     jaxpr, global_out_avals, consts = pe.trace_to_jaxpr_dynamic(
     2024-03-31 13:35:10.701 ERROR:   File "/opt/conda/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
     2024-03-31 13:35:10.702 ERROR:     return func(*args, **kwargs)
     2024-03-31 13:35:10.702 ERROR:   File "/opt/conda/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 2155, in trace_to_jaxpr_dynamic
     2024-03-31 13:35:10.702 ERROR:     jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
     2024-03-31 13:35:10.702 ERROR:   File "/opt/conda/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 2177, in trace_to_subjaxpr_dynamic
     2024-03-31 13:35:10.702 ERROR:     ans = fun.call_wrapped(*in_tracers_)
     2024-03-31 13:35:10.703 ERROR:   File "/opt/conda/lib/python3.9/site-packages/jax/_src/linear_util.py", line 188, in call_wrapped
     2024-03-31 13:35:10.703 ERROR:     ans = self.f(*args, **dict(self.params, **kwargs))
     2024-03-31 13:35:10.703 ERROR:   File "/opt/co-pilot-python/app/app.py", line 165, in f
     2024-03-31 13:35:10.703 ERROR:     kde = jax.scipy.signal.convolve(hist, kernel, mode="same")
     2024-03-31 13:35:10.704 ERROR:   File "/opt/conda/lib/python3.9/site-packages/jax/_src/scipy/signal.py", line 139, in convolve
     2024-03-31 13:35:10.704 ERROR:     return _convolve_nd(in1, in2, mode, precision=precision)
     2024-03-31 13:35:10.704 ERROR:   File "/opt/conda/lib/python3.9/site-packages/jax/_src/scipy/signal.py", line 111, in _convolve_nd
     2024-03-31 13:35:10.704 ERROR:     raise ValueError("One input must be smaller than the other in every dimension.")
     2024-03-31 13:35:10.704 ERROR: jax._src.traceback_util.UnfilteredStackTrace: ValueError: One input must be smaller than the other in every dimension.
     2024-03-31 13:35:10.704 ERROR:
     2024-03-31 13:35:10.705 ERROR: The stack trace below excludes JAX-internal frames.
     2024-03-31 13:35:10.705 ERROR: The preceding is the original exception that occurred, unmodified.
     2024-03-31 13:35:10.705 ERROR:
     2024-03-31 13:35:10.705 ERROR: --------------------
     2024-03-31 13:35:10.705 ERROR:
     2024-03-31 13:35:10.706 ERROR: The above exception was the direct cause of the following exception:
     2024-03-31 13:35:10.706 ERROR:
     2024-03-31 13:35:10.706 ERROR: Traceback (most recent call last):
     2024-03-31 13:35:10.706 ERROR:   File "/opt/co-pilot-python/sdk.py", line 30, in <module>
     2024-03-31 13:35:10.706 ERROR:     sdk = MoveAppsSdk(active_hooks=hooks)
     2024-03-31 13:35:10.706 ERROR:   File "/opt/co-pilot-python/sdk.py", line 23, in __init__
     2024-03-31 13:35:10.707 ERROR:     executor.execute()
     2024-03-31 13:35:10.707 ERROR:   File "/opt/co-pilot-python/sdk/moveapps_execution.py", line 33, in execute
     2024-03-31 13:35:10.707 ERROR:     raise exception
     2024-03-31 13:35:10.707 ERROR:   File "/opt/co-pilot-python/sdk/moveapps_execution.py", line 29, in execute
     2024-03-31 13:35:10.707 ERROR:     output = self.__call_app(data)
     2024-03-31 13:35:10.708 ERROR:   File "/opt/co-pilot-python/sdk/moveapps_execution.py", line 76, in __call_app
     2024-03-31 13:35:10.708 ERROR:     outputs = self._pm.hook.execute(data=data, config=self.env.app_configuration)
     2024-03-31 13:35:10.708 ERROR:   File "/opt/conda/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
     2024-03-31 13:35:10.708 ERROR:     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
     2024-03-31 13:35:10.709 ERROR:   File "/opt/conda/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
     2024-03-31 13:35:10.709 ERROR:     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
     2024-03-31 13:35:10.709 ERROR:   File "/opt/conda/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
     2024-03-31 13:35:10.709 ERROR:     return outcome.get_result()
     2024-03-31 13:35:10.709 ERROR:   File "/opt/conda/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
     2024-03-31 13:35:10.710 ERROR:     raise ex[1].with_traceback(ex[2])
     2024-03-31 13:35:10.710 ERROR:   File "/opt/conda/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
     2024-03-31 13:35:10.710 ERROR:     res = hook_impl.function(*args)
     2024-03-31 13:35:10.710 ERROR:   File "/opt/co-pilot-python/app/app.py", line 66, in execute
     2024-03-31 13:35:10.710 ERROR:     self.execute_once(data, app_config, traj_i)
     2024-03-31 13:35:10.711 ERROR:   File "/opt/co-pilot-python/app/app.py", line 189, in execute_once
     2024-03-31 13:35:10.711 ERROR:     occ = f(p1_x, p1_y, p2_x, p2_y, z, start_time, end_time)
     2024-03-31 13:35:10.711 ERROR:   File "/opt/co-pilot-python/app/app.py", line 165, in f
     2024-03-31 13:35:10.711 ERROR:     kde = jax.scipy.signal.convolve(hist, kernel, mode="same")
     2024-03-31 13:35:10.711 ERROR:   File "/opt/conda/lib/python3.9/site-packages/jax/_src/scipy/signal.py", line 139, in convolve
     2024-03-31 13:35:10.712 ERROR:     return _convolve_nd(in1, in2, mode, precision=precision)
     2024-03-31 13:35:10.712 ERROR:   File "/opt/conda/lib/python3.9/site-packages/jax/_src/scipy/signal.py", line 111, in _convolve_nd
     2024-03-31 13:35:10.712 ERROR:     raise ValueError("One input must be smaller than the other in every dimension.")
     2024-03-31 13:35:10.712 ERROR: ValueError: One input must be smaller than the other in every dimension.
     2024-03-31 13:35:29.747 INFO : gdal_translate -q -co TILED=YES -co COMPRESS=DEFLATE -co ZLEVEL=9 -co PREDICTOR=2 spool/South/S16W074_wgs84.tif cache/South/S16W074_wgs84.tif 2>/dev/null || touch cache/South/S16W074_wgs84.tif
     2024-03-31 13:35:42.982 INFO : curl -s -o spool/South/S15W074_wgs84.tif.temp https://opentopography.s3.sdsc.edu/raster/SRTM_GL1_Ellip/SRTM_GL1_Ellip_srtm/South/S15W074_wgs84.tif && mv spool/South/S15W074_wgs84.tif.temp spool/South/S15W074_wgs84.tif
     2024-03-31 13:36:02.715 INFO : gdal_translate -q -co TILED=YES -co COMPRESS=DEFLATE -co ZLEVEL=9 -co PREDICTOR=2 spool/South/S15W074_wgs84.tif cache/South/S15W074_wgs84.tif 2>/dev/null || touch cache/South/S15W074_wgs84.tif
     2024-03-31 13:36:18.712 INFO : curl -s -o spool/South/S16W073_wgs84.tif.temp https://opentopography.s3.sdsc.edu/raster/SRTM_GL1_Ellip/SRTM_GL1_Ellip_srtm/South/S16W073_wgs84.tif && mv spool/South/S16W073_wgs84.tif.temp spool/South/S16W073_wgs84.tif
     2024-03-31 13:36:38.156 INFO : gdal_translate -q -co TILED=YES -co COMPRESS=DEFLATE -co ZLEVEL=9 -co PREDICTOR=2 spool/South/S16W073_wgs84.tif cache/South/S16W073_wgs84.tif 2>/dev/null || touch cache/South/S16W073_wgs84.tif
     2024-03-31 13:36:52.593 INFO : curl -s -o spool/South/S15W073_wgs84.tif.temp https://opentopography.s3.sdsc.edu/raster/SRTM_GL1_Ellip/SRTM_GL1_Ellip_srtm/South/S15W073_wgs84.tif && mv spool/South/S15W073_wgs84.tif.temp spool/South/S15W073_wgs84.tif
     2024-03-31 13:37:11.531 INFO : gdal_translate -q -co TILED=YES -co COMPRESS=DEFLATE -co ZLEVEL=9 -co PREDICTOR=2 spool/South/S15W073_wgs84.tif cache/South/S15W073_wgs84.tif 2>/dev/null || touch cache/South/S15W073_wgs84.tif
     2024-03-31 13:37:24.231 INFO : curl -s -o spool/South/S16W072_wgs84.tif.temp https://opentopography.s3.sdsc.edu/raster/SRTM_GL1_Ellip/SRTM_GL1_Ellip_srtm/South/S16W072_wgs84.tif && mv spool/South/S16W072_wgs84.tif.temp spool/South/S16W072_wgs84.tif
     2024-03-31 13:37:43.025 INFO : gdal_translate -q -co TILED=YES -co COMPRESS=DEFLATE -co ZLEVEL=9 -co PREDICTOR=2 spool/South/S16W072_wgs84.tif cache/South/S16W072_wgs84.tif 2>/dev/null || touch cache/South/S16W072_wgs84.tif
     2024-03-31 13:37:58.375 INFO : curl -s -o spool/South/S15W072_wgs84.tif.temp https://opentopography.s3.sdsc.edu/raster/SRTM_GL1_Ellip/SRTM_GL1_Ellip_srtm/South/S15W072_wgs84.tif && mv spool/South/S15W072_wgs84.tif.temp spool/South/S15W072_wgs84.tif
     2024-03-31 13:38:17.087 INFO : gdal_translate -q -co TILED=YES -co COMPRESS=DEFLATE -co ZLEVEL=9 -co PREDICTOR=2 spool/South/S15W072_wgs84.tif cache/South/S15W072_wgs84.tif 2>/dev/null || touch cache/South/S15W072_wgs84.tif
     2024-03-31 13:38:31.304 INFO : rm spool/South/S16W073_wgs84.tif spool/South/S15W074_wgs84.tif spool/South/S15W072_wgs84.tif spool/South/S16W074_wgs84.tif spool/South/S15W073_wgs84.tif spool/South/S16W072_wgs84.tif
     2024-03-31 13:38:31.304 INFO : make: Leaving directory '/tmp/tmpjhzduf8x/SRTM1_ELLIP'
     2024-03-31 13:38:31.325 INFO : make: Entering directory '/tmp/tmpjhzduf8x/SRTM1_ELLIP'
     2024-03-31 13:38:31.331 INFO : gdalbuildvrt -q -overwrite SRTM1_ELLIP.vrt cache/South/S16W074_wgs84.tif cache/South/S15W074_wgs84.tif cache/South/S15W073_wgs84.tif cache/South/S16W072_wgs84.tif cache/South/S15W072_wgs84.tif cache/South/S16W073_wgs84.tif
     2024-03-31 13:38:31.398 INFO : make: Leaving directory '/tmp/tmpjhzduf8x/SRTM1_ELLIP'
     2024-03-31 13:38:31.417 INFO : make: Entering directory '/tmp/tmpjhzduf8x/SRTM1_ELLIP'
     2024-03-31 13:38:31.420 INFO : cp SRTM1_ELLIP.vrt SRTM1_ELLIP.39f001cadadf4210acf1bd6b45f52199.vrt
     2024-03-31 13:38:31.426 INFO : make: Leaving directory '/tmp/tmpjhzduf8x/SRTM1_ELLIP'
     2024-03-31 13:38:31.444 INFO : make: Entering directory '/tmp/tmpjhzduf8x/SRTM1_ELLIP'
     2024-03-31 13:38:31.452 INFO : gdal_translate -q -co TILED=YES -co COMPRESS=DEFLATE -co ZLEVEL=9 -co PREDICTOR=2 -projwin -73.242845 -14.1205162 -71.8947382 -15.7594706 SRTM1_ELLIP.39f001cadadf4210acf1bd6b45f52199.vrt DEM.tif
     2024-03-31 13:39:01.411 INFO : rm -f SRTM1_ELLIP.39f001cadadf4210acf1bd6b45f52199.vrt
     2024-03-31 13:39:01.415 INFO : make: Leaving directory '/tmp/tmpjhzduf8x/SRTM1_ELLIP'
![Screenshot 2024-04-01 at 8 43 55 AM](https://github.com/kulits2/3D-BKDE/assets/19862446/2707a1a1-64fe-4b8f-b132-6f1254309a11)
![Screenshot 2024-04-01 at 8 44 00 AM](https://github.com/kulits2/3D-BKDE/assets/19862446/f26f49ec-be70-4a54-958e-f86951137029)
![Screenshot 2024-04-01 at 8 44 05 AM](https://github.com/kulits2/3D-BKDE/assets/19862446/ab450e61-a32c-43d9-89a0-eae5afb11885)

**Comment by kulits2** [comment]
I think it might be due to the size of your dataset. Would you try reducing `Kernel Radius` to `3` and re-running it?

I tried to reproduce the issue on MoveApps, but I ran into problems of my own with the `Upload File from Local System` app.

Peter
